=== Métodos mágicos (métodos dunder).

Python es un lenguaje que tiene un rico conjunto de funciones y operadores 
incorporados que funcionan realmente bien con los tipos incorporados. Por ejemplo, 
el operador + funciona con números, como suma, pero también funciona con cadenas, 
listas y tuplas, como concatenación:

[source,python]
----
>>> 1 + 2.3
3.3
>>> [1, 2, 3] + [4, 5, 6]
[1, 2, 3, 4, 5, 6]
----

Pero, ¿qué es lo que define que `*+*` sea suma para números (enteros y flotantes) 
y concatenación para listas, tuplas, cadenas? ¿Y si quisiera que `*+*` funcionara 
con otros tipos? ¿Podría hacerlo?

La respuesta corta es "sí", y eso ocurre a través de los métodos dunder, 
objeto de estudio en esta sección.

==== 1.1.1 ¿Qué son los métodos dunder?

En Python, los métodos dunder son métodos que permiten a las instancias de una 
clase interactuar con las funciones y operadores incorporados del lenguaje. La 
palabra "dunder" viene de "double underscore", porque los nombres de los métodos 
dunder empiezan y terminan con dos guiones bajos, por ejemplo `\\__str__` o 
`\\__add__`. Normalmente, los métodos dunder no son invocados directamente por 
el programador, lo que hace que parezca que son llamados por arte de magia. Por 
eso, a veces también se hace referencia a los métodos dunder como "métodos mágicos".

Sin embargo, los métodos dunder no se invocan por arte de magia. Simplemente son 
llamados implícitamente por el lenguaje, en momentos específicos que están bien 
definidos, y que dependen del método dunder en cuestión.

==== 1.1.2. El método dunder que todo el mundo conoce

Si ha definido clases en Python, seguro que se ha cruzado con un método dunder: `\\__init__()`. 
El método dunder `\\__init__()` se encarga de inicializar tu instancia de la clase, por lo que 
es ahí donde sueles establecer un montón de atributos relacionados con los argumentos que 
recibió la clase.

Por ejemplo, si estuvieras creando una instancia de una clase Square, crearías el atributo 
para la longitud del lado en `\\__init__()`:

[source,python]
----
class Square:
    def __init__(self, side_length):
        """__init__ es el método dunder que INITcializa la instancia.

        Para crear un cuadrado, se necesita conocer la longitud de su lado,
        de manera se der pasado como un argumento, p. ejm. con Square(1).
        Para asegurar que la instancia conoce su propia longitud de lado,
        es salvada con self.side_length = side_length.
        """
        print("Dentro del init!")
        self.side_length = side_length

sq = Square(1)

# Dentro del init!
----

¡Si ejecutas el código anterior, verá que se imprime el mensaje "Dentro del init!", 
y sin embargo, ¡no llamaste al método `\\__init__()` directamente! El método 
`\\__init__()` fue llamado implícitamente por el lenguaje cuando creaste tu instancia 
de un cuadrado. Los métodos dunder no están destinados a ser llamados directamente 
en el código, sino que son llamados por el intérprete mientras se ejecuta el programa. 
En resumen, los métodos dunder son una herramienta muy útil en Python para definir 
el comportamiento de los objetos en relación a operaciones integradas comunes.

==== 1.1.3 ¿Por qué los métodos dunder empiezan y terminan con dos guiones bajos?

Los dos guiones bajos al principio y al final del nombre de un método dunder no tienen 
ningún significado especial. En otras palabras, el hecho de que el nombre del método 
empiece y termine con dos guiones bajos, en sí mismo, no tiene nada de especial. Los dos 
guiones bajos están ahí sólo para evitar la colisión de nombres con otros métodos 
implementados por programadores desprevenidos.

Piénselo de esta manera: Python tiene un built-in llamado sum. Se puede definir sum para 
que sea otra cosa, pero entonces  se pierde el acceso al built-in que suma cosas, ¿verdad?

[source,python]
----
>>> sum(range(10))
45
>>> sum = 45
>>> sum(range(10))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'int' object is not callable
----

A menudo se ve a principiantes usando sum como nombre de variable porque no saben que sum 
es en realidad una función incorporada (built-in). Si la función incorporada se llamara
`\\__sum__`  en lugar de sum, sería mucho más difícil anularla por error, ¿verdad? Pero 
también sería mucho menos conveniente usar `sum`...

Sin embargo, para los métodos mágicos, no necesitamos que sus nombres sean muy cómodos de 
escribir, porque casi nunca se escribe el nombre de un método mágico. Por lo tanto, Python 
decidió que los métodos mágicos tendrían nombres que empezaran y terminaran con dos guiones 
bajos, ¡para que fuera menos probable que alguien anulara uno de esos métodos por accidente!

En definitiva, los métodos dunder son como cualquier otro método que hayas implementado, con 
la pequeña excepción de que los métodos dunder pueden ser llamados implícitamente por el lenguaje.

==== 1.1.4.Sobreescritura de operadores en Python y métodos dunder

Todos los operadores de Python, como `+`, `==`, e `in`, dependen de métodos dunder para implementar 
su comportamiento.

Por ejemplo, cuando Python encuentra el código `value in container`, en realidad lo convierte 
en una llamada al método dunder apropiado `\\__contains__`, lo que significa que Python en 
realidad ejecuta la expresión `container.\\__contains__(value)`.

Veamos:

[source,python]
----
>>> my_list = [2, 4, 6]

>>> 3 in my_list
False
>>> my_list.__contains__(3)
False

>>> 6 in my_list
True
>>> my_list.__contains__(6)
True
----

Por lo tanto, cuando se quiera sobrecargar ciertos operadores para que 
funcionen de forma personalizada con objetos propios, se necesita 
implementar los respectivos métodos dunder.

Así, si fueras a crear tu propio tipo de contenedor, podrías implementar 
el método dunder `\\__contains__` para asegurarte de que tus contenedores 
pudieran estar en el lado derecho de una expresión con el operador `in`.

==== 1.1.5 Lista de métodos dunder y sus interacciones

Como hemos visto, los métodos dunder son (típicamente) llamados implícitamente 
por el lenguaje... ¿Pero cuándo? El método dunder `\\__init__` es llamado cuando se inicializa una instancia de una clase, pero ¿qué pasa con `\\__str__`, o
`\\__bool__`, u otros métodos dunder?

La siguiente tabla enumera todos los métodos dunder junto con uno o más ejemplos 
de uso (simplificados) que llamarían implícitamente al método dunder respectivo.
Esto puede incluir breves descripciones de situaciones en las que el método
dunder relevante podría ser llamado, o ejemplos de llamadas a funciones que 
dependen de ese método dunder. Estas situaciones de ejemplo pueden tener 
advertencias asociadas, así que asegúrese de leer la documentación sobre los 
métodos dunder siempre que quiera jugar con un método dunder con el que no esté familiarizado.

El orden de las filas de la tabla coincide con el orden en que se mencionan estos 
métodos dunder en la página "Modelo de datos" de la documentación, lo que no implica 
ninguna dependencia entre los distintos métodos dunder, ni tampoco un nivel de 
dificultad en la comprensión de los métodos.

Para una lista completa de los métodos dunder y su descripción ver:
https://mathspp.com/blog/pydonts/dunder-methods#list-of-dunder-methods-and-their-interactions

==== 1.1.6 Explorando un método dunder

Siempre que trabaje con un nuevo método dunder, lo primero que debe hacer es jugar con él.

A continuación, se comparte tres pasos que se pueden usar cuando se explora un nuevo 
método dunder:

. intentar comprender cuándo se llama al método dunder;
. implementar un stub para ese método y activarlo con código; y
. utilizar el método dunder en una situación útil.

A continuación un ejemplo de cómo seguir estos pasos con un ejemplo práctico, el método dunder `\\__missing__`.

¿Para qué sirve el método dunder `\\__missing__`? La documentación del método dunder `\\__missing__` dice:

[quote]
Llamado por `dict.\\__getitem__()` para implementar `self[key]` para subclases de dict cuando la key no está en el diccionario.

En otras palabras, el método dunder `\\__missing__` sólo es relevante para las subclases 
de dict, y es llamado siempre que no podamos encontrar una clave dada en el diccionario.

¿Cómo activar el método dunder? +
¿En qué situaciones, que pueda recrear, se llama al método dunder `\\__missing__`?

Por el texto de la documentación, parece que necesitamos una subclase de diccionario, y luego necesitamos acceder a una clave que no exista en ese diccionario. Por lo tanto, esto debería ser suficiente para activar el método dunder __missing__:

[source, python]
----
class DictSubclass(dict):
    def __missing__(self, key):
        print("Hello, world!")

my_dict = DictSubclass()
my_dict["this key isn't available"]

# Hello, world!
----
Note lo básico que es el código anterior: Sólo se definió un método llamado `\\__missing__`
y se hizo un print, sólo para poder comprobar que `\\__missing__` estaba siendo llamado.

Ahora se realizarán un par de pruebas más, sólo para asegurarnos de que `\\__missing__` 
realmente sólo se llama cuando se intenta obtener el valor de una clave que no existe:

[source, python]
----
class DictSubclass(dict):
    def __missing__(self, key):
        print(f"Missing {key = }")

my_dict = DictSubclass()
my_dict[0] = True
if my_dict[0]:
    print("Key 0 was `True`.")

# Prints: Key 0 was `True`
my_dict[1]  # Prints: Missing key = 1
----

*Utilizar el método dunder en una situación útil* +
Ahora que tenemos una idea más clara de cuándo `\\__missing__` entra en juego, 
podemos usarlo para algo útil. Por ejemplo, podemos intentar implementar `defaultdict` 
basándonos en `\\__missing__`.

`defaultdict` es un contenedor del módulo https://docs.python.org/3/library/collections.html[`collections`], 
y es como un diccionario, excepto que utiliza una fábrica para generar valores 
predefinidos cuando faltan claves.

Por ejemplo, aquí hay una instancia de `defaultdict` que devuelve el valor `0` de forma predetermnada:

[source, python]
----
from collections import defaultdict

olympic_medals = defaultdict(lambda: 0)  # Produce 0 by default
olympic_medals["Phelps"] = 28

print(olympic_medals["Phelps"])  # 28
print(olympic_medals["me"])  # 0
----

Así que, para reimplementar `defaultdict`, necesitamos aceptar una función de 
fábrica, necesitamos guardar esa fábrica, y necesitamos usarla dentro de 
`\\__missing__`.

Sólo como una nota al margen, observe que `defaultdict` no sólo devuelve el valor 
predefinido, sino que también lo asigna a la clave que no estaba allí antes:

[source, python]
----
>>> from collections import defaultdict
>>> olympic_medals = defaultdict(lambda: 0)  # Produce 0 by default
>>> olympic_medals
defaultdict(<function <lambda> at 0x000001F15404F1F0>, {})
>>> # Notice the underlying dictionary is empty -------^^
>>> olympic_medals["me"]
0
>>> olympic_medals
defaultdict(<function <lambda> at 0x000001F15404F1F0>, {'me': 0})
>>> # It's not empty anymore --------------------------^^^^^^^^^
----

Teniendo en cuenta todo esto, he aquí una posible reimplementación de 
`defaultdict`:

[source, python]
----
class my_defaultdict(dict):
    def __init__(self, default_factory, **kwargs):
        super().__init__(**kwargs)
        self.default_factory = default_factory

    def __missing__(self, key):
        """Populate the missing key and return its value."""
        self[key] = self.default_factory()
        return self[key]

olympic_medals = my_defaultdict(lambda: 0)  # Produce 0 by default
olympic_medals["Phelps"] = 28

print(olympic_medals["Phelps"])  # 28
print(olympic_medals["me"])  # 0
----
